INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("potato", "food", 100, "october 4", "october 5");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("tomato", "food", 1000, "october 6", "october 8");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("pepper", "food", 10000, "october 10", "october 15");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("gin", "drink", 100, "october 4", "october 5");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("tonic", "medicine", 100, "october 4", "october 5");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("whiskey", "drink", 100, "october 4", "october 5");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("tylenol", "medicine", 100, "october 4", "october 5");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("garlic", "spice", 100, "october 4", "october 5");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("onion", "food", 100, "october 4", "october 5");
INSERT INTO projects(title, category, funding_goal, start_date, end_date) VALUES ("rosemary", "woman", 100, "october 4", "october 5");

INSERT INTO users(name, age) VALUES ("harry", 11);
INSERT INTO users(name, age) VALUES ("ron", 11);
INSERT INTO users(name, age) VALUES ("hermione", 11);
INSERT INTO users(name, age) VALUES ("ginny", 10);
INSERT INTO users(name, age) VALUES ("neville", 11);
INSERT INTO users(name, age) VALUES ("dumbledore", 110);
INSERT INTO users(name, age) VALUES ("mcgonagall", 55);
INSERT INTO users(name, age) VALUES ("lupin", 33);
INSERT INTO users(name, age) VALUES ("quirrel", 33);
INSERT INTO users(name, age) VALUES ("malfoy", 11);
INSERT INTO users(name, age) VALUES ("crabbe", 11);
INSERT INTO users(name, age) VALUES ("goyle", 11);
INSERT INTO users(name, age) VALUES ("zabini", 11);
INSERT INTO users(name, age) VALUES ("fred", 13);
INSERT INTO users(name, age) VALUES ("george", 13);
INSERT INTO users(name, age) VALUES ("percy", 15);
INSERT INTO users(name, age) VALUES ("hagrid", 61);
INSERT INTO users(name, age) VALUES ("sprout", 55);
INSERT INTO users(name, age) VALUES ("snape", 33);
INSERT INTO users(name, age) VALUES ("flitwick", 65);

INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 4, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 5, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 13);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 14);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 15);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges(amount, user_id, project_id) VALUES (100, 1, 3);

